name: CD

# dev 브랜치에 push 되었을 때,(pr올라온 브랜치가 dev에 merge되었을 때) 실행된다
on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # client에 필요한 npm package들을 설치한다
    - name: Install client npm packages
      run: |
        npm ci --prefix client/
        
    # client의 테스트를 실행한다
    - name: Client test suites
      run: |
        npm run test --prefix client/
        
    # server에 필요한 npm package들을 설치한다
    - name: Install server npm packages
      run: |
        npm ci --prefix server/
        
    # client의 React App을 빌드해서 server의 public디렉토리로 빌드 결과를 이동시킨다
    - name: Build client react-app and move to server public directory
      env: 
        # 필요한 환경변수를 github 저장소의 secrets에 등록해둔다
        REACT_APP_GRAPHQL_URI: ${{ secrets.REACT_APP_GRAPHQL_URI }}
        REACT_APP_SEARCH_URI: ${{ secrets.REACT_APP_SEARCH_URI }}
        REACT_APP_GOOGLE_OAUTH_URI: ${{ secrets.REACT_APP_GOOGLE_OAUTH_URI }}
        REACT_APP_AUTO_SUGGEST_URI: ${{ secrets.REACT_APP_AUTO_SUGGEST_URI }} 
        # CI를 true로 할 경우, warning 도 error로 인식하기 때문에 false를 준다
        CI: false
      run: |
        npm run build --prefix client/
        mkdir server/public
        cp -r client/build/* server/public
        
    # 배포서버에 ssh로 접속해서 구동중인 application을 중지시키고
    # 기존 소스코드를 전부 삭제한다
    - name: stop server via ssh
      uses: appleboy/ssh-action@master
      # ssh 접속을 위해 필요한 HOST, USERNAME, SSH_PRIVATE_KEY는
      # github 저장소 secrets에 등록해둔다
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 kill
          rm -rf ~/app/bmart-4/*
        
    # ssh를 통해 현재 저장소의 소스코드를 서버의 home/app/bmart-4 디렉토리로 이동시킨다
    - name: ssh delivery to aws ec2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        ARGS: '-rltgoDzvO'
        SOURCE: '/'
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TARGET: './app/bmart-4'
    
    # ssh로 접속해서 서버구동에 필요한 .env 파일을 이동시키고
    # 서버를 구동시킨다
    - name: move proudction .env and restart server via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo cp -r ~/app/bmart-4/client/build/* /var/www/app/
          cp ~/app/.env.prod ~/app/bmart-4/server/
          cd ~/app/bmart-4/server
          npm run start:prod
